import './globals.css'

import Footer from '@/components/Footer'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn('bg-secondary-foreground',inter.className)}>
        {children}
        <Footer />
      </body>
    </html>
  )
}
